### ISSUE TITLE
Sub directory "target" not in right place. 

### ISSUE THREAD

**Issue by jasondf** [playframework/play-java-seed.g8#17]
Hello,

When I run command `sbt new playframework/play-java-seed.g8` in a directory, like "_/Users/jason/projects_", and give the project a name "_test_", then the template was applied in "_./test_". But after this project was created, the sub directory "_**target**_" was also in "_/Users/jason/projects_", should I move it to "_/Users/jason/projects/test_" manually?

My sbt version is 0.13.15, and run in Mac OSX 10.11.6.

> ~/projects $ sbt new playframework/play-java-seed.g8
WARN: No sbt.version set in project/build.properties, base directory: /Users/jason/projects
[warn] Executing in batch mode.
[warn]   For better performance, hit [ENTER] to switch to interactive mode, or
[warn]   consider launching sbt without any commands, or explicitly passing 'shell'
[info] Set current project to projects (in build file:/Users/jason/projects/)

> This template generates a Play Java project 

> name [play-java-seed]: test
organization [com.example]: 
scala_version [2.12.2]: 
play_version [2.6.0]: 

> Template applied in ./test

**Comment by wsargent** [comment]
This is https://github.com/sbt/sbt/issues/2835
