### ISSUE TITLE
Unable to run with sbt 1.0.2

### ISSUE THREAD

**Issue by sangongs** [playframework/play-java-seed.g8#25]
OS X EI Capitan version 10.11.4 (15E65)
sbt 1.0.2 installed via brew

---
Platos-MacBook-Pro:Referral plato$ sbt new playframework/play-java-seed.g8
[info] Set current project to referral (in build file:/Users/plato/Documents/Courseworks/2017Fall/TA750/Referral/)

This template generates a Play Java project 

name [play-java-seed]: 
organization [com.example]: 
scala_version [2.12.3]: 
play_version [maven(com.typesafe.play, play_2.12, stable)]: 
sbt_version [maven(org.scala-sbt, sbt, stable)]: 

Template applied in ./play-java-seed

Platos-MacBook-Pro:Referral plato$ cd play-java-seed/
Platos-MacBook-Pro:play-java-seed plato$ sbt run
Getting org.scala-sbt sbt maven(org.scala-sbt, sbt, stable) ...

:: problems summary ::
:::: WARNINGS
		module not found: org.scala-sbt#sbt;maven(org.scala-sbt, sbt, stable)

	==== local: tried

	  /Users/plato/.ivy2/local/org.scala-sbt/sbt/maven(org.scala-sbt, sbt, stable)/ivys/ivy.xml

	  -- artifact org.scala-sbt#sbt;maven(org.scala-sbt, sbt, stable)!sbt.jar:

	  /Users/plato/.ivy2/local/org.scala-sbt/sbt/maven(org.scala-sbt, sbt, stable)/jars/sbt.jar

	==== local-preloaded-ivy: tried

	  file:////Users/plato/.sbt/preloaded/org.scala-sbt/sbt/maven(org.scala-sbt, sbt, stable)/ivys/ivy.xml

	==== local-preloaded: tried

	  file:////Users/plato/.sbt/preloaded/org/scala-sbt/sbt/maven(org.scala-sbt, sbt, stable)/sbt-maven(org.scala-sbt, sbt, stable).pom

	  -- artifact org.scala-sbt#sbt;maven(org.scala-sbt, sbt, stable)!sbt.jar:

	  file:////Users/plato/.sbt/preloaded/org/scala-sbt/sbt/maven(org.scala-sbt, sbt, stable)/sbt-maven(org.scala-sbt, sbt, stable).jar

	==== Maven Central: tried

	  https://repo1.maven.org/maven2/org/scala-sbt/sbt/maven(org.scala-sbt, sbt, stable)/sbt-maven(org.scala-sbt, sbt, stable).pom

	  -- artifact org.scala-sbt#sbt;maven(org.scala-sbt, sbt, stable)!sbt.jar:

	  https://repo1.maven.org/maven2/org/scala-sbt/sbt/maven(org.scala-sbt, sbt, stable)/sbt-maven(org.scala-sbt, sbt, stable).jar

	==== sbt-maven-releases: tried

	  https://repo.scala-sbt.org/scalasbt/maven-releases/org/scala-sbt/sbt/maven(org.scala-sbt, sbt, stable)/sbt-maven(org.scala-sbt, sbt, stable).pom

	  -- artifact org.scala-sbt#sbt;maven(org.scala-sbt, sbt, stable)!sbt.jar:

	  https://repo.scala-sbt.org/scalasbt/maven-releases/org/scala-sbt/sbt/maven(org.scala-sbt, sbt, stable)/sbt-maven(org.scala-sbt, sbt, stable).jar

	==== sbt-maven-snapshots: tried

	  https://repo.scala-sbt.org/scalasbt/maven-snapshots/org/scala-sbt/sbt/maven(org.scala-sbt, sbt, stable)/sbt-maven(org.scala-sbt, sbt, stable).pom

	  -- artifact org.scala-sbt#sbt;maven(org.scala-sbt, sbt, stable)!sbt.jar:

	  https://repo.scala-sbt.org/scalasbt/maven-snapshots/org/scala-sbt/sbt/maven(org.scala-sbt, sbt, stable)/sbt-maven(org.scala-sbt, sbt, stable).jar

	==== typesafe-ivy-releases: tried

	  https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt/maven(org.scala-sbt, sbt, stable)/ivys/ivy.xml

	==== sbt-ivy-snapshots: tried

	  https://repo.scala-sbt.org/scalasbt/ivy-snapshots/org.scala-sbt/sbt/maven(org.scala-sbt, sbt, stable)/ivys/ivy.xml

		::::::::::::::::::::::::::::::::::::::::::::::

		::          UNRESOLVED DEPENDENCIES         ::

		::::::::::::::::::::::::::::::::::::::::::::::

		:: org.scala-sbt#sbt;maven(org.scala-sbt, sbt, stable): not found

		::::::::::::::::::::::::::::::::::::::::::::::

:: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
unresolved dependency: org.scala-sbt#sbt;maven(org.scala-sbt, sbt, stable): not found
Error during sbt execution: Error retrieving required libraries
  (see /Users/plato/.sbt/boot/update.log for complete log)
Error: Could not retrieve sbt maven(org.scala-sbt, sbt, stable)
Platos-MacBook-Pro:play-java-seed plato$

**Comment by ignasi35** [comment]
I don't think this applies anymore. Thanks for reporting @sangongs
